import Link from "next/link";
import { notFound } from "next/navigation";

// Blog posts data
const posts: Record<string, {
  title: string;
  date: string;
  content: string;
}> = {
  "but-what-after-agi": {
    title: "But What After AGI?",
    date: "January 18, 2026",
    content: `Heyy, this is my first real blog and I am very confused about how to contemplate my thoughts and write a little structured, sensible essay. So this piece of text will reflect my thoughts on the existential crisis around AI.

As we all use chatbots like Gemini (free pro :)), ChatGPT, and Perplexity, sometimes I think while doing any mundane task that could easily be done by AI for example, while typing a long paragraph or solving a LeetCode problem. This thought follows with a sense of uselessness and replaceability. I mean, currently the economic contribution of AI agents is negligible, but I think about what happens when their contribution to GDP grows as they are adopted and start providing value in real work. Some of us can see that change as we are at the forefront of tech. But when the data entry job is lost or the sales caller job is gone, wouldn't there be a huge surge in unemployment and a rise in income inequality even more?

Let's imagine an ideal situation where every job is automated. Let's say a man wakes up his room is cleaned by a mop bot, his breakfast was made by an automated kitchen, and the supplies for the breakfast come from an automated farm managed by robot workers. That system is monitored by an intelligent AI. Then, after having breakfast, he takes a bath. The water comes from the nearby river, and its management system is also automated. Then this man watches movies created by diffusion models and generated by AI based on his catalogue, personalized for him. He hangs out in a simulated game that feels like real life, and he is living a life of his dreams he is the starboy of his school, living his teenage years. That's how he completes his day, has dinner, and goes to sleep. He is having the time of his life. And every other human is living some variant of this life, where working is optional.

Sounds too good to be true for me. There has to be some catch. The question is: how does he earn? Let's think these automated systems require energy. Let's say nuclear reactors power these automated systems, manufactured and deployed by other automated systems. Then we are just parasites in this colony. We are like an unemployed person who has convinced their parents to give them money here, the parents are a system that you have to convince to give you money. I could imagine traumatizing Black Mirror shit happening in this scenario.

I thought some form of this situation does exist in our present as well. I like to call them "pseudo workers." These include, as of in India, government employees who are not working up to their productivity, and large corporations where some teams have rotted out from the host. Also, I see the surge in the entertainment sector and social media influencers most of the time people spend is on their phones consuming short-form content (Reels and Shorts). At least people make them as of now, but that seems like a cheap version of cocaine, taking cocaine as the above simulated life. I could see that utopian future does not seem too far if we see it that way.

I think the future is like Schrödinger's cat where it is alive and dead at the same time inside the box. It is only when it is opened that the truth is revealed. The future is both utopian and dystopian, and it is only when it manifests itself that we perceive it.

Thanks for reading through.

_end_of_transmission`,
  },
  "hello-world": {
    title: "Hello World — My First Blog",
    date: "January 17, 2026",
    content: `Today I created my website and this is my first blog!

I'm finally ready to share my corner of the internet. This portfolio will serve as a home for my projects, thoughts, and experiments.

Stay tuned for more posts about tech, design and whatever else catches my interest.

_end_of_transmission`,
  },
};

// Generate static params for all blog posts
export function generateStaticParams() {
  return Object.keys(posts).map((slug) => ({
    slug,
  }));
}

interface PageProps {
  params: Promise<{ slug: string }>;
}

export default async function BlogPost({ params }: PageProps) {
  const { slug } = await params;
  const post = posts[slug];

  if (!post) {
    notFound();
  }

  return (
    <div>
      <Link href="/blog" className="text-muted text-sm hover:underline mb-6 inline-block">
        ← back to blog
      </Link>
      
      <article className="mt-4">
        <header className="mb-6 border-b header-border pb-4">
          <h1 className="text-xl font-bold text-bold mb-2">{post.title}</h1>
          <time className="text-date text-sm">{post.date}</time>
        </header>
        
        <div className="blog-content text-muted leading-relaxed whitespace-pre-line">
          {post.content}
        </div>
      </article>
    </div>
  );
}
